apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "faaast-registry.fullname" . }}-config
  labels:
    {{- include "faaast-registry.labels" . | nindent 4 }}
data:
  application.yaml: |
    server:
      {{- toYaml .Values.server | nindent 6 }}
    cors:
      {{- toYaml .Values.cors | nindent 6 }}
    spring:
      {{- toYaml .Values.spring | nindent 6 }}
