apiVersion: v1
kind: Service
metadata:
  name: {{ include "faaast-registry.fullname" . }}
  labels:
    {{- include "faaast-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
  selector:
    {{- include "faaast-registry.selectorLabels" . | nindent 4 }}
